trigger:
- master  # Adjust this to your default branch

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'OllisAzure'
  appName: 'webapplom'
  resourceGroupName: 'lomazrg'
  zipFileName: 'docs_$(Build.BuildId).zip'
  zipFilePath: '$(Build.ArtifactStagingDirectory)/$(zipFileName)'
  storageAccountName: 'azlomsa '
  containerName: 'documentation'
  blobName: '$(zipFileName)'  

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 8.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'nameofyourfeed'
    includeNuGetOrg: true
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

- script: |
    dotnet tool install -g docfx
    echo '##vso[task.prependpath]$(Agent.ToolsDirectory)/dotnet/tools'
  displayName: 'Install DocFX'

- script: |
    docfx --version
  displayName: 'Verify DocFX Installation'

- script: |
    docfx CommandLineWebApp/docfx.json
  displayName: 'Generate Documentation'
  env:
    PATH: $(PATH):$(HOME)/.dotnet/tools
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'CommandLineWebApp/_site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: $(zipFilePath)
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish/CommandLineWebApp.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/publish/CommandLineWebApp.zip'
    resourceGroupName: $(resourceGroupName)
    appType: 'webAppLinux'