trigger:
- master  # Adjust this to your default branch

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'OllisAzure'
  azureLocation: "'Germany West Central'"
  appServicePlan: 'ASP-LomAzRG-bd9c-B1'
  appSku: 'B1'
  appName: 'webapplom'
  resourceGroupName: 'lomazrg'
  zipFileName: 'docs_$(Build.BuildId).zip'
  zipFilePath: '$(Build.ArtifactStagingDirectory)/$(zipFileName)'
  zipFilePathSafe: '$(zipFilePath).safe'
  storageAccountName: 'azlomsa '
  containerName: 'documentation'
  blobName: '$(zipFileName)'
  websiteUrl: 'https://webapplom.azurewebsites.net'
  githubOwner: mlop3s
  repositoryName: devopsbackup3

steps:
- task: AzureCLI@2
  displayName: 'Check if App has been compromised and delete if needed'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    arguments: >
      -resourceGroupName $(resourceGroupName)
      -appName $(appName)
    inlineScript: |
      # Check the status of the web app
      STATUS=$(az webapp show --resource-group $(resourceGroupName) --name $(appName) --query "state" -o tsv)
      if [ "$STATUS" != "Running" ]; then
        echo "Web app is malfunctioning. Deleting the web app..."
        az webapp delete --resource-group $(resourceGroupName) --name $(appName) 
        echo "##vso[task.setvariable variable=webAppDeleted]true"
      else
        echo "Web app is running. No need to delete."
      fi

- task: AzureCLI@2
  condition: eq(variables['webAppDeleted'], 'true')
  displayName: 'Ensure Resource Group Exists'
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    arguments: >
      -resourceGroupName $(resourceGroupName)
      -resourceGroupLocation $(resourceGroupLocation)
    inlineScript: |
      if ! az group exists --name $(resourceGroupName); then
        az group create --name $(resourceGroupName) --location $(resourceGroupLocation)
      fi
  
- task: AzureCLI@2
  displayName:  'Create appservice plan if missing'
  condition: eq(variables['webAppDeleted'], 'true')
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    arguments: >
      -resourceGroupName $(resourceGroupName)
      -appServicePlan $(appServicePlan)
      -azureLocation $(azureLocation)
      -appSku $(appSku)
    inlineScript: |
      # Check if the service plan exists
      echo $(resourceGroupName)
      echo $(appServicePlan)
      echo $(azureLocation)
      echo $(appSku)
      
      SERVICE_PLAN_EXISTS=$(az appservice plan show --name $(appServicePlan) --resource-group  $(resourceGroupName) --query "name" --output tsv)

      if [ -z "$SERVICE_PLAN_EXISTS" ]; then
        echo "Service plan does not exist. Creating service plan..."
        az appservice plan create --name $(appServicePlan) --resource-group $(resourceGroupName) --location $(azureLocation) --sku $(appSku) --is-linux
      else
        echo "Service plan already exists."
      fi

- task: AzureResourceGroupDeployment@2
  displayName:  'Create web app if missing'
  condition: eq(variables['webAppDeleted'], 'true')
  inputs:
    azureSubscription: $(azureSubscription)
    action: 'Create Or Update Resource Group'
    resourceGroupName: $(resourceGroupName)
    location: $(azureLocation)
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/CommandLineWebApp/Devops/template.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/CommandLineWebApp/Devops/parameters.json'

- task: UseDotNet@2
  displayName: 'Installing .net 8.0'
  inputs:
    packageType: 'sdk'
    version: 8.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
    performMultiLevelLookup: true

- task: DotNetCoreCLI@2
  displayName: 'Restore Nuget Packages'
  inputs:
    command: 'restore'
    feedsToUse: 'select'
    vstsFeed: 'nameofyourfeed'
    includeNuGetOrg: true
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publishing solution'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

- script: |
    dotnet tool install -g docfx
    echo '##vso[task.prependpath]$(Agent.ToolsDirectory)/dotnet/tools'
  displayName: 'Install DocFX'

- script: |
    docfx --version
  displayName: 'Verify DocFX Installation'

- script: |
    docfx CommandLineWebApp/docfx.json
  displayName: 'Generate Documentation'
  env:
    PATH: $(PATH):$(HOME)/.dotnet/tools
- task: ArchiveFiles@2
  displayName: 'Ziping Contents'
  inputs:
    rootFolderOrFile: 'CommandLineWebApp/_site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: $(zipFilePath)
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publising artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish/CommandLineWebApp.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  displayName: 'Upoading app to Azure'
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/publish/CommandLineWebApp.zip'
    resourceGroupName: $(resourceGroupName)
    appType: 'webAppLinux'

- script: |
    if curl -s --head  --request GET $(websiteUrl) | grep "200 OK" > /dev/null; then 
      echo "Website is up"
    else
      echo "Website is down"
      exit 1
    fi
  displayName: 'Ping Azure Webapp'

- script: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
    sudo apt-add-repository https://cli.github.com/packages
    sudo apt update
    sudo apt install gh
  displayName: 'Install GitHub CLI'

- script: |
    gh auth login --with-token <<< "$GH_TOKEN"
    if gh repo view $GITHUB_OWNER/$REPOSITORY_NAME > /dev/null 2>&1; then
      echo "Repository $REPO_NAME already exists."
    else
      echo "Creating repository $REPO_NAME."
      gh repo create $GITHUB_OWNER/$REPOSITORY_NAME --public --description "AZ400 backup repo" --confirm
    fi
  displayName: 'Check if GitHub repository exists'
  env:
    GH_TOKEN: $(GITHUB_PAT) 
    GITHUB_OWNER: $(githubOwner)
    REPOSITORY_NAME: $(repositoryName)

- script: |
    git clone https://mlop3s:$(GITHUB_PAT)@github.com/$GITHUB_OWNER/$REPOSITORY_NAME.git
  displayName: 'Clone git'
  env:
    GH_TOKEN: $(GITHUB_PAT)
    GITHUB_OWNER: $(githubOwner)
    REPOSITORY_NAME: $(repositoryName)    

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.ArtifactStagingDirectory)
    Contents: $(zipFileName) # You can use wildcards like '**/*.txt' to copy multiple files
    TargetFolder: $(repositoryName)
  displayName: 'Copy file to target folder'

- script: |
    echo "Running script in the src folder"
    git config --global user.name 'github-actions[bot]'
    git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    git add .
    git status
    git commit -m "Automated Commit"
    git push
  displayName: 'Commiting new zip file to github'
  workingDirectory: $(repositoryName)

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $ip = (Invoke-WebRequest -Uri "http://ifconfig.me/ip").Content.Trim()
      Write-Output "Agent IP Address: $ip"
  displayName: 'Get Agent IP Address'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Define the source and destination file paths
      $sourceFilePath = "$(Build.SourcesDirectory)/path/to/oldfilename.txt"
      $destinationFilePath = "$(Build.SourcesDirectory)/path/to/newfilename.txt"
      
      # Rename the file
      Rename-Item -Path $(zipFilePath) -NewName $(zipFilePathSafe)'

      Write-Host "File renamed from $(zipFilePath) to $(zipFilePathSafe)"
  displayName: "Rename file for e-mail attachment"

- task: PowerShell@2
  inputs:
    targetType: 'filePath'
    filePath: '$(System.DefaultWorkingDirectory)/CommandLineWebApp/Devops/SendMail.ps1'
    arguments: '-pathToFile $(zipFilePathSafe)'
    pwsh: false
  displayName: 'Send Email Notification'
  env:
    EmailPassword: $(EmailPassword)
    Debuging: $(Debuging)
    SecretDebuging: $(SecretDebuging)

    
    