trigger:
- master  # Adjust this to your default branch

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  azureSubscription: 'OllisAzure'
  appName: 'webapplom'
  resourceGroupName: 'lomazrg'
  zipFileName: 'docs_$(Build.BuildId).zip'
  zipFilePath: '$(Build.ArtifactStagingDirectory)/$(zipFileName)'
  storageAccountName: 'azlomsa '
  containerName: 'documentation'
  blobName: '$(zipFileName)'  

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: 8.x
    installationPath: $(Agent.ToolsDirectory)/dotnet
    performMultiLevelLookup: true

- script: |
    dotnet restore CommandBased/CommandLineWebApp.sln
  displayName: 'Restore NuGet Packages'

- script: |
    dotnet build CommandBased/CommandLineWebApp.sln --configuration $(buildConfiguration)
  displayName: 'Build Solution'

- script: |
    dotnet test CommandBased/CommandLineWebApp.sln --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run Tests'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'

- script: |
    dotnet tool install -g docfx
    echo '##vso[task.prependpath]$(Agent.ToolsDirectory)/dotnet/tools'
  displayName: 'Install DocFX'

- script: |
    docfx --version
  displayName: 'Verify DocFX Installation'

- script: |
    docfx CommandBased/docfx.json
  displayName: 'Generate Documentation'
  env:
    PATH: $(PATH):$(HOME)/.dotnet/tools
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'CommandBased/_site'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: $(zipFilePath)
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/publish/CommandBased.zip'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: $(azureSubscription)
    appName: $(appName)
    package: '$(Build.ArtifactStagingDirectory)/publish/CommandBased.zip'
    resourceGroupName: $(resourceGroupName)
    appType: 'webAppLinux'